package enums;

public enum ConfigProperties {
	KOOCO_URL, KOOCO_BALANCE_PAGE_URL,KOOCO_TOTAL_ORDER_COUNT, KOOCO_USERNAME, KOOCO_PASSWORD, KOOCO_FILEPATH, KOOCO_LEVEL, KOOCO_TAKE_BACKUP,
	KOOCO_SAVE_FILE, KOOCO_SEND_MAIL;
}
